-- =============================================================================
-- TAPX - schema.sql
-- Run this file FIRST in the Supabase SQL Editor (or via psql).
-- Then run policies.sql, then seed.sql.
--
-- This script is idempotent: it can be re-run safely.
--
-- SECURITY MODEL
--   * Every balance / progression value is written ONLY by SECURITY DEFINER
--     functions (process_tap, purchase_upgrade, claim_daily_reward,
--     claim_milestone) that validate server-side.
--   * Clients can never write coins, taps, level, XP or upgrade levels
--     directly. A guard trigger rejects any attempt.
--   * The Supabase service_role key is never used by the frontend.
-- =============================================================================

create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- 0. Helpers
-- -----------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- XP required to advance FROM p_level TO p_level + 1
create or replace function public.xp_to_next(p_level integer)
returns bigint
language sql
immutable
as $$
  select (100::bigint * greatest(coalesce(p_level, 1), 1))
       + (25::bigint * (greatest(coalesce(p_level, 1), 1)::bigint * greatest(coalesce(p_level, 1), 1)));
$$;

-- 0.1 Game tuning constants (documented, enforced in process_tap)
create or replace function public.game_limits()
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'min_tap_interval_ms', 40,      -- fastest physically plausible tap cadence
    'max_taps_per_batch', 250,     -- hard cap accepted from a client batch
    'max_coins_per_batch', 1000000,
    'combo_window_ms', 900,        -- average interval required to sustain combo
    'max_combo', 10000,
    'min_batch_gap_ms', 25,        -- fastest accepted round trip between batches
    'ad_event_min_gap_seconds', 60
  );
$$;

-- -----------------------------------------------------------------------------
-- 1. Tables
-- -----------------------------------------------------------------------------

create table if not exists public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  username      text not null,
  display_name  text,
  avatar_url    text,
  coins         bigint not null default 0 check (coins >= 0),
  total_taps    bigint not null default 0 check (total_taps >= 0),
  coins_per_tap bigint not null default 1 check (coins_per_tap > 0),
  level         integer not null default 1 check (level >= 1),
  experience    bigint not null default 0 check (experience >= 0),
  highest_combo integer not null default 0 check (highest_combo >= 0),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists public.game_state (
  user_id             uuid primary key references auth.users(id) on delete cascade,
  combo               integer not null default 0 check (combo >= 0),
  last_tap_at         timestamptz,
  last_batch_at       timestamptz,
  sound_enabled       boolean not null default true,
  vibration_enabled   boolean not null default true,
  last_daily_reward   timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create table if not exists public.upgrades (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  name        text not null,
  description text,
  icon        text not null default 'bolt',
  base_cost   bigint not null check (base_cost > 0),
  growth      numeric not null default 1.15 check (growth > 1),
  multiplier  numeric not null default 1.15 check (multiplier > 0),
  max_level   integer not null default 20 check (max_level > 0),
  sort_order  integer not null default 0,
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.user_upgrades (
  user_id    uuid not null references auth.users(id) on delete cascade,
  upgrade_id bigint not null references public.upgrades(id) on delete cascade,
  level      integer not null default 0 check (level >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, upgrade_id)
);

create table if not exists public.milestones (
  id             bigint generated by default as identity primary key,
  name           text not null,
  description    text,
  tap_requirement bigint not null check (tap_requirement > 0),
  reward_coins   bigint not null check (reward_coins >= 0),
  sort_order     integer not null default 0,
  active         boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists public.user_milestones (
  user_id      uuid not null references auth.users(id) on delete cascade,
  milestone_id bigint not null references public.milestones(id) on delete cascade,
  claimed_at   timestamptz not null default now(),
  primary key (user_id, milestone_id)
);

create table if not exists public.daily_rewards (
  user_id         uuid primary key references auth.users(id) on delete cascade,
  last_claimed_at timestamptz,
  streak          integer not null default 0 check (streak >= 0)
);

-- Legitimate application-side ad events only.
-- This table NEVER manufactures impressions: it records a user opening or
-- interacting with a real, visible placement that exists in ad_placements.
-- Reporting to the ad network is done exclusively by the official network code.
create table if not exists public.ad_events (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  placement   text not null,
  event_type  text not null,
  created_at  timestamptz not null default now(),
  constraint ad_events_event_type_check
    check (event_type in ('placement_view', 'placement_click', 'reward_view', 'reward_complete'))
);

create table if not exists public.admin_users (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  role       text not null default 'admin' check (role in ('admin', 'owner', 'moderator')),
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key        text primary key,
  value      jsonb not null,
  updated_at timestamptz not null default now()
);

-- Staleness marker. Every function definition, grant, policy and validation
-- rule in this file is applied with "create or replace" / "if not exists", so
-- re-running the file is always safe. Bumping this value on every schema change
-- is what makes a database that was never re-run detectable instead of silent:
-- a browser can compare it against the version shipped in js/config.js and warn
-- that the live function definitions are behind the frontend.
insert into public.app_settings (key, value)
values ('schema_version', '6')
on conflict (key) do update
  set value = excluded.value, updated_at = now();

create table if not exists public.ad_placements (
  id           bigint generated by default as identity primary key,
  slug         text not null unique,
  label        text not null,
  location     text not null,
  description  text,
  -- The exact official publisher snippet, pasted by an admin in
  -- Admin > Ads. Never written by the app, never generated, never guessed.
  code         text,
  enabled      boolean not null default true,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

   -- Migration for databases created before the ad-code column existed.
   -- Safe to re-run.
   alter table public.ad_placements add column if not exists code text;
   
   -- Script-only ad formats.
   --
   -- These are deliberately NOT part of ad_placements. A popunder and a
   -- smartlink produce no visible box in the page, so giving them one of the
   -- five visible containers would leave an empty bordered "Sponsored" frame
   -- and misrepresent them to anyone reviewing the page.
   --
   --   popunder  the network's script tag, loaded once per page view, and only
   --             ever opened by the user's own click on a link that leaves the
   --             game. Never automatic, never on a tap, never refreshed.
   --   smartlink a URL prefix used to wrap outbound links. The one link that
   --             may use it is the explicit Exit button. The privacy, terms and
   --             support links are never wrapped.
   create table if not exists public.ad_scripts (
     kind        text primary key check (kind in ('popunder', 'smartlink')),
     -- The exact official snippet, or the smartlink URL prefix. Pasted by an
     -- admin, never written by the app, never generated, never guessed.
     code        text,
     enabled     boolean not null default false,
     created_at  timestamptz not null default now(),
     updated_at  timestamptz not null default now()
   );
   

create table if not exists public.site_announcements (
  id         bigint generated by default as identity primary key,
  title      text not null,
  message    text not null,
  active     boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- 2. Indexes
-- -----------------------------------------------------------------------------

create index if not exists profiles_total_taps_idx   on public.profiles (total_taps desc);
create index if not exists profiles_created_at_idx   on public.profiles (created_at desc);
create index if not exists profiles_username_idx     on public.profiles (lower(username));
create index if not exists user_upgrades_user_idx    on public.user_upgrades (user_id);
create index if not exists user_milestones_user_idx  on public.user_milestones (user_id);
create index if not exists ad_events_user_created_idx on public.ad_events (user_id, created_at desc);
create index if not exists ad_events_created_idx     on public.ad_events (created_at desc);
create index if not exists ad_events_type_idx        on public.ad_events (event_type, created_at desc);
create index if not exists announcements_active_idx  on public.site_announcements (active, created_at desc);
create index if not exists upgrades_active_idx       on public.upgrades (active, sort_order);

-- -----------------------------------------------------------------------------
-- 3. Triggers
-- -----------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_base  text;
  v_name  text;
  v_try   integer := 0;
begin
  v_base := lower(coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'username'), ''),
    nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
    'player'
  ));
  v_base := left(regexp_replace(v_base, '[^a-z0-9_]', '', 'g'), 20);
  if v_base = '' then
    v_base := 'player';
  end if;

  v_name := v_base;
  while exists (select 1 from public.profiles where lower(username) = v_name) and v_try < 8 loop
    v_name := v_base || '_' || substr(md5(gen_random_uuid()::text), 1, 4);
    v_try := v_try + 1;
  end loop;

  v_name := left(v_name, 24);

  insert into public.profiles (id, username, display_name)
  values (new.id, v_name, left(coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), v_name), 40))
  on conflict (id) do nothing;

  insert into public.game_state (user_id) values (new.id) on conflict (user_id) do nothing;
  insert into public.daily_rewards (user_id) values (new.id) on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists game_state_updated_at on public.game_state;
create trigger game_state_updated_at before update on public.game_state
  for each row execute function public.set_updated_at();

drop trigger if exists upgrades_updated_at on public.upgrades;
create trigger upgrades_updated_at before update on public.upgrades
  for each row execute function public.set_updated_at();

drop trigger if exists milestones_updated_at on public.milestones;
create trigger milestones_updated_at before update on public.milestones
  for each row execute function public.set_updated_at();

drop trigger if exists settings_updated_at on public.app_settings;
create trigger settings_updated_at before update on public.app_settings
  for each row execute function public.set_updated_at();

drop trigger if exists placements_updated_at on public.ad_placements;
create trigger placements_updated_at before update on public.ad_placements
  for each row execute function public.set_updated_at();

drop trigger if exists scripts_updated_at on public.ad_scripts;
create trigger scripts_updated_at before update on public.ad_scripts
  for each row execute function public.set_updated_at();

drop trigger if exists announcements_updated_at on public.site_announcements;
create trigger announcements_updated_at before update on public.site_announcements
  for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- 4. Write guards
--    Clients may only touch cosmetic columns. Everything economic is written
--    exclusively by the SECURITY DEFINER functions below.
-- -----------------------------------------------------------------------------

create or replace function public.guard_profile_write()
returns trigger
language plpgsql
as $$
begin
  -- Allow the owner (postgres / service_role / SECURITY DEFINER) to proceed.
  if current_user not in ('authenticated', 'anon') then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.coins          := 0;
    new.total_taps     := 0;
    new.level          := 1;
    new.experience     := 0;
    new.highest_combo  := 0;
    new.coins_per_tap  := 1;
    return new;
  end if;

  if new.coins is distinct from old.coins
     or new.total_taps is distinct from old.total_taps
     or new.coins_per_tap is distinct from old.coins_per_tap
     or new.level is distinct from old.level
     or new.experience is distinct from old.experience
     or new.highest_combo is distinct from old.highest_combo then
    raise exception 'Protected column: progression values are updated by the server only'
      using errcode = '42501';
  end if;

  if new.username is null or btrim(new.username) = ''
     or length(new.username) > 24
     or new.username !~ '^[a-z0-9_]{3,24}$' then
    raise exception 'Invalid username: use 3-24 characters (a-z, 0-9, underscore)'
      using errcode = '22023';
  end if;

  new.display_name := left(coalesce(new.display_name, new.username), 40);
  return new;
end;
$$;

drop trigger if exists profiles_guard_write on public.profiles;
create trigger profiles_guard_write
  before insert or update on public.profiles
  for each row execute function public.guard_profile_write();

create or replace function public.guard_game_state_write()
returns trigger
language plpgsql
as $$
begin
  if current_user not in ('authenticated', 'anon') then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.combo := 0;
    return new;
  end if;

  if new.combo is distinct from old.combo
     or new.last_tap_at is distinct from old.last_tap_at
     or new.last_batch_at is distinct from old.last_batch_at
     or new.last_daily_reward is distinct from old.last_daily_reward then
    raise exception 'Protected column: combo/tap state is updated by the server only'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

drop trigger if exists game_state_guard_write on public.game_state;
create trigger game_state_guard_write
  before insert or update on public.game_state
  for each row execute function public.guard_game_state_write();

-- Ad events: must reference a real, enabled placement and be rate limited.
create or replace function public.guard_ad_event()
returns trigger
language plpgsql
as $$
declare
  v_gap integer;
begin
  if not exists (
    select 1 from public.ad_placements p
    where p.slug = new.placement
  ) then
    raise exception 'Unknown ad placement: %', new.placement using errcode = '22023';
  end if;

  if not exists (
    select 1 from public.ad_placements p
    where p.slug = new.placement and p.enabled
  ) then
    raise exception 'Ad placement is disabled: %', new.placement using errcode = '22023';
  end if;

  v_gap := (public.game_limits() ->> 'ad_event_min_gap_seconds')::integer;

  -- Silently skip (return NULL => row is not inserted) anything more frequent
  -- than the network's own minimum reporting cadence.
  if exists (
    select 1 from public.ad_events e
    where e.user_id = new.user_id
      and e.placement = new.placement
      and e.created_at > now() - make_interval(secs => v_gap)
  ) then
    return null;
  end if;

  return new;
end;
$$;

drop trigger if exists ad_events_guard on public.ad_events;
create trigger ad_events_guard
  before insert on public.ad_events
  for each row execute function public.guard_ad_event();

-- -----------------------------------------------------------------------------
-- 5. Authorization helpers
-- -----------------------------------------------------------------------------

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users au where au.user_id = auth.uid()
  );
$$;

create or replace function public.require_admin()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;
  if not exists (select 1 from public.admin_users au where au.user_id = auth.uid()) then
    raise exception 'Admin privileges required' using errcode = '42501';
  end if;
end;
$$;

-- Creates any missing per-user rows (self-healing, own user only).
create or replace function public.ensure_user_state(p_user uuid default auth.uid())
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_user is null or p_user <> auth.uid() then
    raise exception 'Not allowed' using errcode = '42501';
  end if;

  insert into public.profiles (id, username, display_name)
  values (p_user, 'player_' || left(replace(p_user::text, '-', ''), 8), 'Player')
  on conflict (id) do nothing;

  insert into public.game_state (user_id) values (p_user) on conflict (user_id) do nothing;
  insert into public.daily_rewards (user_id) values (p_user) on conflict (user_id) do nothing;
end;
$$;

-- -----------------------------------------------------------------------------
-- 6. Gameplay RPCs
-- -----------------------------------------------------------------------------

-- 6.1 Register a tap batch. All rewards are computed server-side.
create or replace function public.process_tap(
  p_tap_count  integer,
  p_duration_ms integer default 0,
  p_client_combo integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user      uuid := auth.uid();
  v_lim       jsonb := public.game_limits();
  v_min_int   integer := (v_lim ->> 'min_tap_interval_ms')::integer;
  v_max_batch integer := (v_lim ->> 'max_taps_per_batch')::integer;
  v_max_coins bigint   := (v_lim ->> 'max_coins_per_batch')::bigint;
  v_combo_win integer := (v_lim ->> 'combo_window_ms')::integer;
  v_max_combo integer := (v_lim ->> 'max_combo')::integer;
  v_min_gap   integer := (v_lim ->> 'min_batch_gap_ms')::integer;

  v_p        public.profiles%rowtype;
  v_s        public.game_state%rowtype;
  v_taps     integer;
  v_elapsed  numeric := 0;
  v_span     numeric;
  v_allowed  integer;
  v_avg      numeric;

  v_tap_power integer := 0;
  v_combo_boost integer := 0;
  v_crit      integer := 0;
  v_bonus     integer := 0;

  v_base      numeric;
  v_mult      numeric;
  v_per_tap   numeric;
  v_coins     numeric;
  v_gain      bigint;
  v_crit_hit  boolean := false;
  v_crit_chance numeric;

  v_exp       bigint;
  v_level     integer;
  v_new_combo integer;
  v_time      timestamptz := now();
begin
  if v_user is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;

  perform public.ensure_user_state(v_user);

  -- --- validate input -------------------------------------------------------
  if p_tap_count is null or p_tap_count < 1 or p_tap_count > v_max_batch then
    raise exception 'Invalid tap count (expected 1..%)', v_max_batch using errcode = '22023';
  end if;
  v_taps := p_tap_count;
  if p_duration_ms is null or p_duration_ms < 0 or p_duration_ms > 600000 then
    p_duration_ms := 0;
  end if;

  select * into v_s from public.game_state where user_id = v_user for update;
  select * into v_p from public.profiles where id = v_user for update;

  -- Elapsed wall-clock time since the previous accepted batch.
  if v_s.last_batch_at is not null then
    v_elapsed := extract(epoch from (v_time - v_s.last_batch_at)) * 1000;
  else
    v_elapsed := 60000;
  end if;
  v_elapsed := greatest(v_elapsed, v_min_gap::numeric);

  -- Reject impossible tap density (server-side anti-abuse). The count is
  -- CLAMPED rather than rejected so that laggy clients are not punished.
  v_allowed := floor(v_elapsed / v_min_int)::integer + 2;
  if v_taps > v_allowed then
    v_taps := greatest(v_allowed, 1);
  end if;

  -- Duration used for combo math: the larger of the client-reported span and
  -- the real server-side gap (never trusts the client to make itself faster).
  v_span := greatest(p_duration_ms::numeric, v_elapsed);

  -- --- upgrade levels -------------------------------------------------------
  select
    coalesce(max(uu.level) filter (where u.slug = 'tap_power'), 0),
    coalesce(max(uu.level) filter (where u.slug = 'combo_boost'), 0),
    coalesce(max(uu.level) filter (where u.slug = 'critical_tap'), 0),
    coalesce(max(uu.level) filter (where u.slug = 'bonus_multiplier'), 0)
  into v_tap_power, v_combo_boost, v_crit, v_bonus
  from public.user_upgrades uu
  join public.upgrades u on u.id = uu.upgrade_id
  where uu.user_id = v_user;

  -- --- coin math ------------------------------------------------------------
  v_base := (v_p.coins_per_tap::numeric + (v_p.level - 1) * 0.1)
            * power(1.15, v_tap_power);
  v_mult := power(1.10, greatest(v_combo_boost, 0))
            * power(1.25, greatest(v_bonus, 0));
  v_per_tap := v_base * v_mult;

  v_coins := trunc(v_per_tap * v_taps);

  v_crit_chance := least(v_crit * 0.02, 0.30);
  if v_crit_chance > 0 and random() < v_crit_chance then
    v_coins := trunc(v_coins * 2);
    v_crit_hit := true;
  end if;

  v_gain := least(greatest(trunc(v_coins), 0), v_max_coins);

  -- --- combo ----------------------------------------------------------------
  v_avg := v_span / v_taps::numeric;
  if v_avg <= v_combo_win then
    v_new_combo := least(v_s.combo + v_taps, v_max_combo);
  else
    v_new_combo := 0;
  end if;

  -- --- xp / level -----------------------------------------------------------
  v_exp := v_p.experience + v_taps + floor(v_gain / 2);
  v_level := v_p.level;
  while v_exp >= public.xp_to_next(v_level) and v_level < 1000 loop
    v_exp := v_exp - public.xp_to_next(v_level);
    v_level := v_level + 1;
  end loop;

  -- --- persist --------------------------------------------------------------
  update public.profiles
     set coins = coins + v_gain,
         total_taps = total_taps + v_taps,
         experience = v_exp,
         level = v_level,
         highest_combo = greatest(highest_combo, v_new_combo)
   where id = v_user;

  update public.game_state
     set combo = v_new_combo,
         last_tap_at = v_time,
         last_batch_at = v_time
   where user_id = v_user;

  return jsonb_build_object(
    'ok', true,
    'coins', v_p.coins + v_gain,
    'coins_gained', v_gain,
    'total_taps', v_p.total_taps + v_taps,
    'taps_accepted', v_taps,
    'taps_rejected', p_tap_count - v_taps,
    'coins_per_tap', trunc(v_per_tap)::bigint,
    'level', v_level,
    'leveled_up', v_level > v_p.level,
    'experience', v_exp,
    'xp_to_next', public.xp_to_next(v_level),
    'combo', v_new_combo,
    'highest_combo', greatest(v_p.highest_combo, v_new_combo),
    'critical', v_crit_hit
  );
end;
$$;

-- 6.2 Buy an upgrade with earned coins. Atomic.
create or replace function public.purchase_upgrade(p_upgrade_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_p    public.profiles%rowtype;
  v_u    public.upgrades%rowtype;
  v_lvl  integer;
  v_cost bigint;
begin
  if v_user is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;

  perform public.ensure_user_state(v_user);

  select * into v_u from public.upgrades where id = p_upgrade_id and active;
  if not found then
    raise exception 'Upgrade not found' using errcode = 'P0002';
  end if;

  select * into v_p from public.profiles where id = v_user for update;

  select coalesce(level, 0) into v_lvl
    from public.user_upgrades where user_id = v_user and upgrade_id = p_upgrade_id;
  v_lvl := coalesce(v_lvl, 0);

  if v_lvl >= v_u.max_level then
    raise exception 'Upgrade is already at max level' using errcode = '22023';
  end if;

  -- Cost of the NEXT level, computed server-side from the catalog.
  v_cost := greatest(1, trunc(v_u.base_cost * power(v_u.growth, greatest(v_lvl, 0))));

  if v_p.coins < v_cost then
    raise exception 'Not enough coins: need %, you have %', v_cost, v_p.coins
      using errcode = 'P0001', detail = json_build_object('reason', 'insufficient_coins', 'cost', v_cost, 'coins', v_p.coins)::text;
  end if;

  insert into public.user_upgrades (user_id, upgrade_id, level)
  values (v_user, p_upgrade_id, 1)
  on conflict (user_id, upgrade_id) do update set level = public.user_upgrades.level + 1, updated_at = now();

  update public.profiles set coins = coins - v_cost where id = v_user;

  return jsonb_build_object(
    'ok', true,
    'upgrade_id', p_upgrade_id,
    'level', v_lvl + 1,
    'max_level', v_u.max_level,
    'cost', v_cost,
    'coins', v_p.coins - v_cost
  );
end;
$$;

-- Cost preview (safe to call as often as you like, mutates nothing).
create or replace function public.upgrade_cost(p_upgrade_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_u   public.upgrades%rowtype;
  v_lvl integer := 0;
begin
  select * into v_u from public.upgrades where id = p_upgrade_id;
  if not found then
    raise exception 'Upgrade not found' using errcode = 'P0002';
  end if;

  select coalesce(uu.level, 0) into v_lvl
  from public.user_upgrades uu
  where uu.user_id = auth.uid() and uu.upgrade_id = p_upgrade_id;

  return jsonb_build_object(
    'upgrade_id', p_upgrade_id,
    'level', v_lvl,
    'max_level', v_u.max_level,
    'cost', greatest(1, trunc(v_u.base_cost * power(v_u.growth, greatest(v_lvl, 0)))),
    'maxed', v_lvl >= v_u.max_level
  );
end;
$$;

-- 6.3 Daily reward: one legitimate claim per 24 hours.
create or replace function public.claim_daily_reward()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user   uuid := auth.uid();
  v_d      public.daily_rewards%rowtype;
  v_streak integer;
  v_reward bigint := 0;
  v_table  jsonb;
  v_coins  bigint;
begin
  if v_user is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;

  perform public.ensure_user_state(v_user);

  select * into v_d from public.daily_rewards where user_id = v_user for update;

  if v_d.last_claimed_at is not null and v_d.last_claimed_at > now() - interval '24 hours' then
    raise exception 'Daily reward already claimed'
      using errcode = 'P0001',
            detail = json_build_object(
              'reason', 'too_soon',
              'next_at', v_d.last_claimed_at + interval '24 hours',
              'streak', v_d.streak
            )::text;
  end if;

  select value into v_table from public.app_settings where key = 'daily_rewards';
  if v_table is null or jsonb_typeof(v_table) <> 'array' then
    v_table := '[100,150,250,400,600,800,1200]'::jsonb;
  end if;

  if v_d.last_claimed_at is null
     or v_d.last_claimed_at <= now() - interval '48 hours' then
    v_streak := 1;                     -- missed a day: streak restarts
  else
    v_streak := least(v_d.streak + 1, jsonb_array_length(v_table));
  end if;

  -- Read the configured amount defensively: never trust the shape of jsonb.
  select case
           when (v_table ->> (v_streak - 1)) ~ '^[0-9]{1,18}$'
             then (v_table ->> (v_streak - 1))::bigint
           else 0
         end
    into v_reward;

  update public.daily_rewards
     set streak = v_streak, last_claimed_at = now()
   where user_id = v_user;

  update public.profiles set coins = coins + v_reward where id = v_user
    returning coins into v_coins;

  return jsonb_build_object(
    'ok', true,
    'streak', v_streak,
    'reward', v_reward,
    'coins', v_coins,
    'next_at', now() + interval '24 hours'
  );
end;
$$;

-- 6.4 Milestone claim: once per milestone, requirement verified server-side.
create or replace function public.claim_milestone(p_milestone_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_m    public.milestones%rowtype;
  v_p    public.profiles%rowtype;
  v_coins bigint;
begin
  if v_user is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;

  select * into v_m from public.milestones where id = p_milestone_id and active;
  if not found then
    raise exception 'Milestone not found' using errcode = 'P0002';
  end if;

  select * into v_p from public.profiles where id = v_user for update;

  if v_p.total_taps < v_m.tap_requirement then
    raise exception 'Requirement not met'
      using errcode = 'P0001',
            detail = json_build_object('reason', 'requirement_not_met', 'required', v_m.tap_requirement, 'taps', v_p.total_taps)::text;
  end if;

  begin
    insert into public.user_milestones (user_id, milestone_id)
    values (v_user, p_milestone_id);
  exception when unique_violation then
    raise exception 'Milestone already claimed'
      using errcode = 'P0001',
            detail = json_build_object('reason', 'already_claimed')::text;
  end;

  update public.profiles set coins = coins + v_m.reward_coins where id = v_user
    returning coins into v_coins;

  return jsonb_build_object(
    'ok', true,
    'milestone_id', p_milestone_id,
    'name', v_m.name,
    'reward', v_m.reward_coins,
    'coins', v_coins
  );
end;
$$;

-- 6.5 Log one legitimate application-side ad event.
--     The trigger guard_ad_event() rejects unknown or disabled placements,
--     restricts event_type to a fixed list and rate limits to one event per
--     placement per minute. This function cannot create impressions: it only
--     records that the app did something with a real, enabled placement.
create or replace function public.record_ad_event(
  p_placement  text,
  p_event_type text default 'placement_view'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;

  insert into public.ad_events (user_id, placement, event_type)
  values (auth.uid(), p_placement, p_event_type);

  return jsonb_build_object('ok', true);
exception
  when check_violation or foreign_key_violation then
    raise exception 'Invalid ad event' using errcode = '22023';
end;
$$;

-- -----------------------------------------------------------------------------
-- 7. Read APIs
-- -----------------------------------------------------------------------------

-- 7.1 Full player state used by the game UI.
create or replace function public.get_player_state()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_p    public.profiles%rowtype;
  v_s    public.game_state%rowtype;
  v_d    public.daily_rewards%rowtype;
begin
  if v_user is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;

  select * into v_p from public.profiles where id = v_user;
  select * into v_s from public.game_state where user_id = v_user;
  select * into v_d from public.daily_rewards where user_id = v_user;

  if not found then
    return jsonb_build_object('ok', false, 'missing_state', true);
  end if;

  return jsonb_build_object(
    'ok', true,
    'id', v_p.id,
    'username', v_p.username,
    'display_name', v_p.display_name,
    'avatar_url', v_p.avatar_url,
    'coins', v_p.coins,
    'total_taps', v_p.total_taps,
    'coins_per_tap', v_p.coins_per_tap,
    'level', v_p.level,
    'experience', v_p.experience,
    'xp_to_next', public.xp_to_next(v_p.level),
    'highest_combo', v_p.highest_combo,
    'combo', coalesce(v_s.combo, 0),
    'sound_enabled', coalesce(v_s.sound_enabled, true),
    'vibration_enabled', coalesce(v_s.vibration_enabled, true),
    'created_at', v_p.created_at,
    'daily_streak', coalesce(v_d.streak, 0),
    'daily_last_claimed_at', v_d.last_claimed_at,
    'is_admin', exists (select 1 from public.admin_users au where au.user_id = v_user)
  );
end;
$$;

-- 7.2 Statistics panel.
create or replace function public.get_user_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_p    public.profiles%rowtype;
  v_rank bigint;
begin
  if v_user is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;

  select * into v_p from public.profiles where id = v_user;
  if not found then
    raise exception 'Profile not found' using errcode = 'P0002';
  end if;

  select count(*) + 1 into v_rank
  from public.profiles where total_taps > v_p.total_taps;

  return jsonb_build_object(
    'ok', true,
    'total_taps', v_p.total_taps,
    'coins', v_p.coins,
    'level', v_p.level,
    'experience', v_p.experience,
    'xp_to_next', public.xp_to_next(v_p.level),
    'highest_combo', v_p.highest_combo,
    'global_rank', v_rank,
    'created_at', v_p.created_at,
    'upgrades', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', u.id, 'slug', u.slug, 'name', u.name, 'icon', u.icon,
        'level', uu.level, 'max_level', u.max_level
      ) order by u.sort_order)
      from public.user_upgrades uu
      join public.upgrades u on u.id = uu.upgrade_id
      where uu.user_id = v_user and uu.level > 0
    ), '[]'::jsonb),
    'milestones', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', m.id, 'name', m.name, 'tap_requirement', m.tap_requirement,
        'reward_coins', m.reward_coins, 'claimed', true, 'claimed_at', um.claimed_at
      ) order by m.sort_order)
      from public.user_milestones um
      join public.milestones m on m.id = um.milestone_id
      where um.user_id = v_user
    ), '[]'::jsonb)
  );
end;
$$;

-- 7.3 Public configuration: app settings, placements, announcements.
--      Only non-sensitive keys are exposed.
create or replace function public.get_public_config()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'settings', coalesce((
      select jsonb_object_agg(key, value)
      from public.app_settings
        where key in (
          'app_name', 'tagline', 'maintenance_mode', 'support_email',
          'privacy_url', 'terms_url', 'tap_value', 'daily_rewards',
          'xp_curve', 'reward_offer_enabled', 'ads_enabled',
          'schema_version'
        )
    ), '{}'::jsonb),
      'placements', coalesce((
        select jsonb_agg(jsonb_build_object(
          'slug', slug, 'label', label, 'location', location,
          'description', description, 'enabled', enabled, 'code', code
        ) order by sort_order)
        from public.ad_placements where enabled
      ), '[]'::jsonb),
      -- Script-only formats. Only enabled rows are returned, so an admin can
      -- see the switch state in the panel but a client never receives a
      -- disabled snippet. A popunder is only ever opened by the user's own
      -- click on the Exit link; it is never requested on load or on a tap.
      'scripts', coalesce((
        select jsonb_agg(jsonb_build_object(
          'kind', kind, 'code', code
        ) order by kind)
        from public.ad_scripts where enabled
      ), '[]'::jsonb),
    'announcements', coalesce((
      select jsonb_agg(jsonb_build_object('id', id, 'title', title, 'message', message, 'created_at', created_at) order by created_at desc)
      from public.site_announcements where active
    ), '[]'::jsonb),
    'milestones', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', id, 'name', name, 'description', description,
        'tap_requirement', tap_requirement, 'reward_coins', reward_coins
      ) order by sort_order)
      from public.milestones where active
    ), '[]'::jsonb),
    'upgrades', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', id, 'slug', slug, 'name', name, 'description', description, 'icon', icon,
        'base_cost', base_cost, 'growth', growth, 'multiplier', multiplier, 'max_level', max_level
      ) order by sort_order)
      from public.upgrades where active
    ), '[]'::jsonb)
  );
$$;

-- 7.4 Milestone progress for the current user.
create or replace function public.get_milestone_status()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', m.id,
    'name', m.name,
    'description', m.description,
    'tap_requirement', m.tap_requirement,
    'reward_coins', m.reward_coins,
    'claimed', (um.user_id is not null),
    'unlocked', coalesce(p.total_taps, 0) >= m.tap_requirement
  ) order by m.sort_order), '[]'::jsonb)
  from public.milestones m
  left join public.user_milestones um on um.milestone_id = m.id and um.user_id = auth.uid()
  left join public.profiles p on p.id = auth.uid()
  where m.active;
$$;

-- -----------------------------------------------------------------------------
-- 8. Admin RPCs (all guarded by public.require_admin())
-- -----------------------------------------------------------------------------

create or replace function public.admin_overview()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  perform public.require_admin();

  return jsonb_build_object(
    'ok', true,
    'users_total', (select count(*) from public.profiles),
    'users_24h', (select count(*) from public.profiles where created_at > now() - interval '24 hours'),
    'dau_24h', (select count(*) from public.game_state where last_batch_at > now() - interval '24 hours'),
    'dau_7d',  (select count(*) from public.game_state where last_batch_at > now() - interval '7 days'),
    'total_taps', coalesce((select sum(total_taps) from public.profiles), 0),
    'total_coins', coalesce((select sum(coins) from public.profiles), 0),
    'avg_taps', coalesce((select round(avg(total_taps), 1) from public.profiles), 0),
    'milestones_claimed', (select count(*) from public.user_milestones),
    'upgrades_purchased', (select count(*) from public.user_upgrades where level > 0),
    'daily_claims_24h', (select count(*) from public.daily_rewards where last_claimed_at > now() - interval '24 hours'),
    'ad_events_total', (select count(*) from public.ad_events),
    'ad_events_24h', (select count(*) from public.ad_events where created_at > now() - interval '24 hours'),
    'ad_events_by_type', coalesce((
      select jsonb_object_agg(event_type, n) from (
        select event_type, count(*) as n from public.ad_events group by event_type
      ) s
    ), '{}'::jsonb),
    'top_players', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', t.id, 'username', t.username, 'total_taps', t.total_taps,
        'coins', t.coins, 'level', t.level
      ) order by t.total_taps desc)
      from (
        select id, username, total_taps, coins, level
        from public.profiles
        order by total_taps desc
        limit 10
      ) t
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_search_users(
  p_query  text default null,
  p_limit  integer default 25,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_q text;
begin
  perform public.require_admin();

  v_q := lower(trim(coalesce(p_query, '')));
  p_limit := least(greatest(coalesce(p_limit, 25), 1), 100);
  p_offset := greatest(coalesce(p_offset, 0), 0);

  return jsonb_build_object(
    'ok', true,
    'total', (
      select count(*) from public.profiles
      where v_q = ''
         or lower(username) like '%' || v_q || '%'
         or lower(coalesce(display_name, '')) like '%' || v_q || '%'
         or id::text like v_q || '%'
    ),
    'users', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', p.id,
        'username', p.username,
        'display_name', p.display_name,
        'email', u.email,
        'total_taps', p.total_taps,
        'coins', p.coins,
        'level', p.level,
        'created_at', p.created_at,
        'last_seen', gs.last_batch_at,
        'is_admin', (au.user_id is not null)
      ) order by p.created_at desc)
      from (
        select * from public.profiles
        where v_q = ''
           or lower(username) like '%' || v_q || '%'
           or lower(coalesce(display_name, '')) like '%' || v_q || '%'
           or id::text like v_q || '%'
        order by created_at desc
        limit p_limit offset p_offset
      ) p
      left join auth.users u on u.id = p.id
      left join public.game_state gs on gs.user_id = p.id
      left join public.admin_users au on au.user_id = p.id
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_set_setting(p_key text, p_value jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();

  if p_key is null or length(trim(p_key)) = 0 or length(p_key) > 64 then
    raise exception 'Invalid setting key' using errcode = '22023';
  end if;
  if p_key = 'tap_value' then
    if (p_value #>> '{}')::numeric < 1 or (p_value #>> '{}')::numeric > 1000 then
      raise exception 'tap_value must be between 1 and 1000' using errcode = '22023';
    end if;
  end if;

  insert into public.app_settings (key, value) values (p_key, coalesce(p_value, 'null'::jsonb))
  on conflict (key) do update set value = excluded.value, updated_at = now();

  return jsonb_build_object('ok', true, 'key', p_key);
end;
$$;

create or replace function public.admin_save_placement(
  p_id          bigint   default null,
  p_slug        text     default '',
  p_label       text     default '',
  p_location    text     default 'top',
  p_description text     default null,
  p_enabled     boolean  default true,
  p_sort_order  integer  default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id       bigint;
  v_slug     text;
  v_location text;
begin
  perform public.require_admin();

  v_slug := lower(btrim(coalesce(p_slug, '')));
  v_location := lower(btrim(coalesce(p_location, 'top')));

  if v_slug !~ '^[a-z0-9_-]{2,32}$' then
    raise exception
      'Invalid slug "%". Use 2-32 characters: a-z, 0-9, underscore or hyphen. Spaces are not allowed.', v_slug
      using errcode = '22023';
  end if;

  -- Only the containers that exist in index.html. A placement pointing
  -- anywhere else would be saved but never render, so it is rejected here.
  --
  -- The hint matters: this whitelist grew from three locations to five. A
  -- database that still has the older admin_save_placement() rejects a valid
  -- location such as "stats" with this exact message, and the most likely
  -- cause is always a stale function definition rather than bad input.
  if v_location not in ('top', 'stats', 'between', 'inline', 'bottom') then
    raise exception
      'Invalid location "%". Must be top, stats, between, inline or bottom. '
      'If that location is one of those five, this database is running an '
      'outdated admin_save_placement(): re-run supabase/schema.sql, which is '
      'idempotent. Check with: select value from public.app_settings where key = ''schema_version''.',
      v_location
      using errcode = '22023';
  end if;

  if btrim(coalesce(p_label, '')) = '' then
    raise exception 'Label is required.' using errcode = '22023';
  end if;

  if exists (
    select 1 from public.ad_placements
     where location = v_location and (p_id is null or id <> p_id)
  ) then
    raise exception
      'A placement already uses the "%" container. Edit that one instead.', v_location
      using errcode = '22023';
  end if;

  if p_id is null then
    insert into public.ad_placements (slug, label, location, description, enabled, sort_order)
    values (v_slug, left(btrim(p_label), 60), v_location, p_description, coalesce(p_enabled, true), coalesce(p_sort_order, 0))
    returning id into v_id;
  else
    update public.ad_placements
       set slug = v_slug,
           label = left(btrim(p_label), 60),
           location = v_location,
           description = p_description,
           enabled = coalesce(p_enabled, true),
           sort_order = coalesce(p_sort_order, 0)
     where id = p_id
    returning id into v_id;

    if v_id is null then
      raise exception 'Placement not found' using errcode = 'P0002';
    end if;
  end if;

  return jsonb_build_object('ok', true, 'id', v_id);
end;
$$;

create or replace function public.admin_ensure_placements()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();

  -- Restores the canonical containers, one per index.html ad slot.
  -- Deliberately does NOT touch `code` (saved snippets survive) and does NOT
  -- touch `enabled` (restoring never switches ads on behind the owner's back).
  insert into public.ad_placements (slug, label, location, description, enabled, sort_order)
  values
    ('top', 'Sponsored', 'top',
     'Visible banner directly under the XP card. The official Adsterra code for this placement goes inside the #ad-top container in index.html.',
     false, 1),
    ('stats', 'Sponsored', 'stats',
     'Visible unit directly under the coin/XP chip row, above the XP bar. Official code goes inside #ad-stats. This is NOT the Stats screen.',
     false, 2),
    ('between', 'Sponsored', 'between',
     'Visible unit after the tap area, above the disclaimer. Official code goes inside #ad-between.',
     false, 3),
    ('inline', 'Sponsored', 'inline',
     'Visible in-content unit after the disclaimer. Official code goes inside #ad-inline.',
     false, 4),
    ('bottom', 'Sponsored', 'bottom',
     'Visible unit above the bottom navigation. Official code goes inside #ad-bottom.',
     false, 5)
  on conflict (slug) do update
    set label = excluded.label,
        location = excluded.location,
        description = excluded.description,
        sort_order = excluded.sort_order,
        updated_at = now();

  return jsonb_build_object(
    'ok', true,
    'count', (select count(*) from public.ad_placements)
  );
end;
$$;

create or replace function public.admin_set_ad_code(p_slug text, p_code text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code   text;
  v_existed boolean;
begin
  perform public.require_admin();

  if p_slug is null or p_slug !~ '^[a-z0-9_-]{2,32}$' then
    raise exception 'Invalid placement slug (a-z, 0-9, underscore, hyphen)'
      using errcode = '22023';
  end if;

  v_code := nullif(btrim(coalesce(p_code, '')), '');

  if v_code is not null and length(v_code) > 20000 then
    raise exception 'Ad code is too long (max 20000 characters)'
      using errcode = '22023';
  end if;

  -- Refuse snippets that would destroy the page if injected after load.
  if v_code is not null and v_code ~ 'document[[:space:]]*\.[[:space:]]*write[[:space:]]*\(' then
    raise exception
      'This snippet uses document.write(), which cannot work when injected after page load and would blank the page. Ask your network for the standard script tag version.'
      using errcode = '22023';
  end if;

  select exists (select 1 from public.ad_placements where slug = p_slug)
    into v_existed;

  if not v_existed then
    raise exception 'Placement not found: %', p_slug using errcode = 'P0002';
  end if;

  update public.ad_placements
     set code = v_code, updated_at = now()
   where slug = p_slug;

  return jsonb_build_object(
    'ok', true,
    'slug', p_slug,
    'has_code', v_code is not null,
    'code_length', coalesce(length(v_code), 0)
  );
end;
$$;

-- 7.x Admin write for the two script-only ad formats.
--
-- Unlike admin_save_placement() there is no location here: a popunder and a
-- smartlink have no container. The upsert keeps a pasted snippet across
-- re-runs, and a blank p_code clears it rather than storing an empty string.
create or replace function public.admin_set_ad_script(
  p_kind    text,
  p_code    text default null,
  p_enabled boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_kind text;
  v_code text;
begin
  perform public.require_admin();

  v_kind := lower(btrim(coalesce(p_kind, '')));

  if v_kind not in ('popunder', 'smartlink') then
    raise exception
      'Invalid script kind "%". Must be popunder or smartlink.', v_kind
      using errcode = '22023';
  end if;

  v_code := nullif(btrim(coalesce(p_code, '')), '');

  if v_code is not null and length(v_code) > 20000 then
    raise exception 'Ad script is too long (max 20000 characters)'
      using errcode = '22023';
  end if;

  if v_code is not null
     and v_code ~ 'document[[:space:]]*\.[[:space:]]*write[[:space:]]*\(' then
    raise exception
      'This snippet uses document.write(), which cannot work when injected after page load and would blank the page. Ask your network for the standard script tag version.'
      using errcode = '22023';
  end if;

  -- A smartlink is a URL, not a script. Refuse anything that is obviously not
  -- one, because a malformed prefix would silently break every Exit click.
  if v_kind = 'smartlink' and v_code is not null
     and v_code !~ '^https?://' then
    raise exception
      'A smartlink must be an http:// or https:// URL. Paste the smartlink address, including any ?url= or &url= prefix your network gave you.'
      using errcode = '22023';
  end if;

  -- Refuse to enable a format that has nothing to load, so the admin panel
  -- can never show a switch that silently does nothing.
  if p_enabled and v_code is null then
    raise exception
      'Cannot enable % because no code has been saved for it yet.', v_kind
      using errcode = '22023';
  end if;

  insert into public.ad_scripts (kind, code, enabled)
  values (v_kind, v_code, coalesce(p_enabled, false))
  on conflict (kind) do update
    set code    = excluded.code,
        enabled = excluded.enabled,
        updated_at = now();

  return jsonb_build_object(
    'ok', true,
    'kind', v_kind,
    'has_code', v_code is not null,
    'code_length', coalesce(length(v_code), 0),
    'enabled', coalesce(p_enabled, false)
  );
end;
$$;

create or replace function public.admin_ensure_ad_scripts()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();

  -- Both default to disabled and empty. A restore must never turn advertising
  -- on by itself, and must never overwrite a pasted snippet.
  insert into public.ad_scripts (kind, enabled)
  values ('popunder', false), ('smartlink', false)
  on conflict (kind) do nothing;

  return jsonb_build_object(
    'ok', true,
    'count', (select count(*) from public.ad_scripts)
  );
end;
$$;

create or replace function public.admin_delete_placement(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();
  delete from public.ad_placements where id = p_id;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.admin_save_upgrade(
  p_id          bigint   default null,
  p_slug        text     default '',
  p_name        text     default '',
  p_description text     default null,
  p_icon        text     default 'bolt',
  p_base_cost   bigint   default 100,
  p_growth      numeric  default 1.15,
  p_multiplier  numeric  default 1.15,
  p_max_level   integer  default 20,
  p_sort_order  integer  default 0,
  p_active      boolean  default true
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  perform public.require_admin();

  if coalesce(p_base_cost, 0) < 1 or coalesce(p_max_level, 0) < 1
     or coalesce(p_growth, 0) <= 1 or coalesce(p_multiplier, 0) <= 0 then
    raise exception 'Invalid upgrade configuration' using errcode = '22023';
  end if;

  if p_id is null then
    insert into public.upgrades (slug, name, description, icon, base_cost, growth, multiplier, max_level, sort_order, active)
    values (p_slug, left(p_name, 60), p_description, coalesce(p_icon, 'bolt'),
            p_base_cost, p_growth, p_multiplier, p_max_level, coalesce(p_sort_order, 0), coalesce(p_active, true))
    returning id into v_id;
  else
    update public.upgrades
       set slug = p_slug, name = left(p_name, 60), description = p_description,
           icon = coalesce(p_icon, 'bolt'), base_cost = p_base_cost, growth = p_growth,
           multiplier = p_multiplier, max_level = p_max_level,
           sort_order = coalesce(p_sort_order, 0), active = coalesce(p_active, true)
     where id = p_id
    returning id into v_id;
  end if;

  return jsonb_build_object('ok', true, 'id', v_id);
end;
$$;

create or replace function public.admin_delete_upgrade(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();
  delete from public.upgrades where id = p_id;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.admin_save_milestone(
  p_id             bigint   default null,
  p_name           text     default '',
  p_description    text     default null,
  p_tap_requirement bigint  default 100,
  p_reward_coins   bigint   default 500,
  p_sort_order     integer  default 0,
  p_active         boolean  default true
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  perform public.require_admin();

  if coalesce(p_tap_requirement, 0) < 1 then
    raise exception 'tap_requirement must be at least 1' using errcode = '22023';
  end if;

  if p_id is null then
    insert into public.milestones (name, description, tap_requirement, reward_coins, sort_order, active)
    values (left(p_name, 60), p_description, p_tap_requirement,
            greatest(coalesce(p_reward_coins, 0), 0), coalesce(p_sort_order, 0), coalesce(p_active, true))
    returning id into v_id;
  else
    update public.milestones
       set name = left(p_name, 60), description = p_description,
           tap_requirement = p_tap_requirement, reward_coins = greatest(coalesce(p_reward_coins, 0), 0),
           sort_order = coalesce(p_sort_order, 0), active = coalesce(p_active, true)
     where id = p_id
    returning id into v_id;
  end if;

  return jsonb_build_object('ok', true, 'id', v_id);
end;
$$;

create or replace function public.admin_delete_milestone(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();
  delete from public.milestones where id = p_id;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.admin_save_announcement(
  p_id      bigint   default null,
  p_title   text     default '',
  p_message text     default '',
  p_active  boolean  default true
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  perform public.require_admin();

  if p_id is null then
    insert into public.site_announcements (title, message, active)
    values (left(p_title, 80), left(p_message, 500), coalesce(p_active, true))
    returning id into v_id;
  else
    update public.site_announcements
       set title = left(p_title, 80), message = left(p_message, 500), active = coalesce(p_active, true)
     where id = p_id
    returning id into v_id;
  end if;

  return jsonb_build_object('ok', true, 'id', v_id);
end;
$$;

create or replace function public.admin_delete_announcement(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();
  delete from public.site_announcements where id = p_id;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.admin_adjust_coins(
  p_user_id uuid,
  p_delta   bigint,
  p_reason  text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_coins bigint;
begin
  perform public.require_admin();

  if abs(coalesce(p_delta, 0)) > 1000000000 then
    raise exception 'Delta out of allowed range' using errcode = '22023';
  end if;

  update public.profiles
     set coins = greatest(0, coins + coalesce(p_delta, 0))
   where id = p_user_id
  returning coins into v_coins;

  if v_coins is null then
    raise exception 'User not found' using errcode = 'P0002';
  end if;

  return jsonb_build_object('ok', true, 'coins', v_coins, 'reason', p_reason);
end;
$$;

create or replace function public.admin_set_admin(
  p_user_id uuid,
  p_role    text default 'admin',
  p_grant   boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();

  if p_user_id = auth.uid() and not coalesce(p_grant, false) then
    raise exception 'You cannot remove your own admin role' using errcode = '42501';
  end if;

  if coalesce(p_grant, false) then
    insert into public.admin_users (user_id, role) values (p_user_id, coalesce(p_role, 'admin'))
    on conflict (user_id) do update set role = excluded.role;
  else
    delete from public.admin_users where user_id = p_user_id;
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.admin_list_settings()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object('ok', true, 'settings', (
    select jsonb_object_agg(key, value) from public.app_settings
  ));
$$;

-- -----------------------------------------------------------------------------
-- 9. Enable RLS on everything
--    (Policies live in policies.sql and are mirrored below so that a single
--     run of schema.sql produces a working, locked-down database.)
-- -----------------------------------------------------------------------------

alter table public.profiles            enable row level security;
alter table public.game_state          enable row level security;
alter table public.upgrades            enable row level security;
alter table public.user_upgrades       enable row level security;
alter table public.milestones          enable row level security;
alter table public.user_milestones     enable row level security;
alter table public.daily_rewards       enable row level security;
alter table public.ad_events           enable row level security;
alter table public.admin_users         enable row level security;
alter table public.app_settings        enable row level security;
alter table public.ad_placements       enable row level security;
alter table public.ad_scripts          enable row level security;
alter table public.site_announcements  enable row level security;

-- -----------------------------------------------------------------------------
-- 10. RLS policies + column grants
--     A copy of supabase/policies.sql is inlined below so that running this
--     single file yields a fully secured database. policies.sql contains the
--     same statements grouped for review/audit; both are idempotent.
--     NOTE: this file is written for the Supabase SQL Editor, so it contains
--     no psql meta-commands.
-- -----------------------------------------------------------------------------

-- profiles --------------------------------------------------------------------
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select to authenticated using (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
  for insert to authenticated with check (id = auth.uid());

-- game_state ------------------------------------------------------------------
drop policy if exists "game_state_select_own" on public.game_state;
create policy "game_state_select_own" on public.game_state
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "game_state_update_own" on public.game_state;
create policy "game_state_update_own" on public.game_state
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- upgrades / milestones / placements: public catalogue ------------------------
drop policy if exists "upgrades_public_read" on public.upgrades;
create policy "upgrades_public_read" on public.upgrades
  for select to anon, authenticated using (active or public.is_admin());

drop policy if exists "upgrades_admin_write" on public.upgrades;
create policy "upgrades_admin_write" on public.upgrades
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "milestones_public_read" on public.milestones;
create policy "milestones_public_read" on public.milestones
  for select to anon, authenticated using (active or public.is_admin());

drop policy if exists "milestones_admin_write" on public.milestones;
create policy "milestones_admin_write" on public.milestones
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "placements_public_read" on public.ad_placements;
create policy "placements_public_read" on public.ad_placements
  for select to anon, authenticated using (true);

drop policy if exists "placements_admin_write" on public.ad_placements;
create policy "placements_admin_write" on public.ad_placements
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ad_scripts. Reads are admin-only: the game never queries this table directly,
-- it receives the enabled snippets through get_public_config(), which is
-- SECURITY DEFINER. So a signed-in non-admin cannot list the table or read a
-- disabled row. Writes go through admin_set_ad_script(), which additionally
-- calls require_admin() and re-validates the snippet.
drop policy if exists "scripts_admin_read" on public.ad_scripts;
create policy "scripts_admin_read" on public.ad_scripts
  for select to authenticated using (public.is_admin());

drop policy if exists "scripts_admin_write" on public.ad_scripts;
create policy "scripts_admin_write" on public.ad_scripts
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- per-user data: read only, written exclusively by server functions -----------
drop policy if exists "user_upgrades_select_own" on public.user_upgrades;
create policy "user_upgrades_select_own" on public.user_upgrades
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "user_milestones_select_own" on public.user_milestones;
create policy "user_milestones_select_own" on public.user_milestones
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "daily_rewards_select_own" on public.daily_rewards;
create policy "daily_rewards_select_own" on public.daily_rewards
  for select to authenticated using (user_id = auth.uid());

-- ad events --------------------------------------------------------------------
drop policy if exists "ad_events_insert_own" on public.ad_events;
create policy "ad_events_insert_own" on public.ad_events
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "ad_events_select_own" on public.ad_events;
create policy "ad_events_select_own" on public.ad_events
  for select to authenticated using (user_id = auth.uid() or public.is_admin());

-- admin_users -------------------------------------------------------------------
drop policy if exists "admin_users_select_own" on public.admin_users;
create policy "admin_users_select_own" on public.admin_users
  for select to authenticated using (user_id = auth.uid() or public.is_admin());

-- app settings / announcements ----------------------------------------------------
drop policy if exists "settings_public_read" on public.app_settings;
create policy "settings_public_read" on public.app_settings
  for select to anon, authenticated using (true);

drop policy if exists "settings_admin_write" on public.app_settings;
create policy "settings_admin_write" on public.app_settings
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "announcements_public_read" on public.site_announcements;
create policy "announcements_public_read" on public.site_announcements
  for select to anon, authenticated using (active or public.is_admin());

drop policy if exists "announcements_admin_write" on public.site_announcements;
create policy "announcements_admin_write" on public.site_announcements
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Column level privileges: clients may only change cosmetic columns -----------
revoke insert, delete on table public.profiles     from authenticated;
revoke update on table public.profiles             from authenticated;
grant  update (username, display_name, avatar_url) on public.profiles to authenticated;

revoke insert, delete on table public.game_state   from authenticated;
revoke update on table public.game_state           from authenticated;
grant  update (sound_enabled, vibration_enabled)  on public.game_state to authenticated;

revoke all on table public.user_upgrades  from anon, authenticated;
grant  select on table public.user_upgrades  to authenticated;

revoke all on table public.user_milestones from anon, authenticated;
grant  select on table public.user_milestones to authenticated;

revoke all on table public.daily_rewards  from anon;
grant  select on table public.daily_rewards  to authenticated;

revoke all on table public.ad_events from anon;
revoke update, delete on table public.ad_events from authenticated;
grant insert, select on table public.ad_events to authenticated;

revoke all on table public.admin_users from anon;
revoke insert, update, delete on table public.admin_users from authenticated;
grant select on table public.admin_users to authenticated;

revoke insert, update, delete on table public.app_settings from anon, authenticated;

-- Function privileges: no function is executable by PUBLIC by default -------
revoke execute on function public.set_updated_at()            from public;
revoke execute on function public.xp_to_next(integer)         from public;
revoke execute on function public.game_limits()               from public;
revoke execute on function public.handle_new_user()           from public;
revoke execute on function public.guard_profile_write()       from public;
revoke execute on function public.guard_game_state_write()    from public;
revoke execute on function public.guard_ad_event()            from public;
revoke execute on function public.require_admin()             from public;
revoke execute on function public.ensure_user_state(uuid)     from public;
revoke execute on function public.is_admin()                  from public;

-- is_admin() must be executable by anon as well: the public catalogue policies
-- evaluate it, and an anonymous request would otherwise fail with
-- "permission denied for function is_admin" instead of returning false.
grant execute on function public.is_admin()                 to anon, authenticated;
grant execute on function public.ensure_user_state(uuid)    to authenticated;
grant execute on function public.process_tap(integer, integer, integer) to authenticated;
grant execute on function public.purchase_upgrade(bigint)   to authenticated;
grant execute on function public.upgrade_cost(bigint)       to authenticated;
grant execute on function public.claim_daily_reward()       to authenticated;
grant execute on function public.claim_milestone(bigint)    to authenticated;
grant execute on function public.record_ad_event(text, text) to authenticated;
grant execute on function public.get_player_state()         to authenticated;
grant execute on function public.get_user_stats()           to authenticated;
grant execute on function public.get_milestone_status()      to authenticated;
grant execute on function public.get_public_config()        to anon, authenticated;

grant execute on function public.admin_overview()                              to authenticated;
grant execute on function public.admin_search_users(text, integer, integer)     to authenticated;
grant execute on function public.admin_list_settings()                          to authenticated;
grant execute on function public.admin_set_setting(text, jsonb)                 to authenticated;
grant execute on function public.admin_save_placement(bigint, text, text, text, text, boolean, integer) to authenticated;
grant execute on function public.admin_ensure_placements()                 to authenticated;
grant execute on function public.admin_set_ad_code(text, text)             to authenticated;
grant execute on function public.admin_set_ad_script(text, text, boolean)   to authenticated;
grant execute on function public.admin_ensure_ad_scripts()                  to authenticated;
grant execute on function public.admin_delete_placement(bigint)            to authenticated;
grant execute on function public.admin_save_upgrade(bigint, text, text, text, text, bigint, numeric, numeric, integer, integer, boolean) to authenticated;
grant execute on function public.admin_delete_upgrade(bigint)                   to authenticated;
grant execute on function public.admin_save_milestone(bigint, text, text, bigint, bigint, integer, boolean) to authenticated;
grant execute on function public.admin_delete_milestone(bigint)                 to authenticated;
grant execute on function public.admin_save_announcement(bigint, text, text, boolean) to authenticated;
grant execute on function public.admin_delete_announcement(bigint)               to authenticated;
grant execute on function public.admin_adjust_coins(uuid, bigint, text)         to authenticated;
grant execute on function public.admin_set_admin(uuid, text, boolean)           to authenticated;

-- =============================================================================
-- End of schema.sql
-- =============================================================================
